Repository hoangsonww/The-MovieVerse-Database, pull requests merged in 2024-02, with the labels that each got.

#17 Fix minor UI bugs - Frontend
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  index.html
Labels: bug, documentation, enhancement, good first issue

#25 Fix: Updated mobile app
  MovieVerse-Mobile/404.html
  MovieVerse-Mobile/index.html
  MovieVerse-Mobile/index.js
  MovieVerse-Mobile/manifest.json
  MovieVerse-Mobile/package-lock.json
  MovieVerse-Mobile/package.json
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/index.js
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/package-lock.json
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/package.json
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/sitemap.xml
  MovieVerse-Mobile/platforms/ios/CordovaLib/CordovaLib.xcodeproj/xcuserdata/davidnguyen.xcuserdatad/xcschemes/xcschememanagement.plist
  MovieVerse-Mobile/platforms/ios/MovieVerse.xcworkspace/xcuserdata/davidnguyen.xcuserdatad/UserInterfaceState.xcuserstate
  MovieVerse-Mobile/robots.txt
  MovieVerse-Mobile/sitemap.xml
  index.html
  microfrontend-layout.html
Labels: enhancement, good first issue

#27 Fix app styling issues
  .idea/The-MovieVerse-Database.iml
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/favorites.js
Labels: bug, enhancement

#29 Added IMDB Ratings for Movies & TV Series
  MovieVerse-Frontend/css/style.css
  MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Frontend/js/tv-details.js
Labels: enhancement, good first issue

#32 Overall App Enhancements - Bug Fixes
  MovieVerse-Frontend/404.html
  MovieVerse-Frontend/App.vue
  MovieVerse-Frontend/README.md
  MovieVerse-Frontend/index.html
  MovieVerse-Frontend/index.js
  MovieVerse-Frontend/microfrontend-layout.html
  index.html
Labels: bug, enhancement

#36 Homepage Enhancements - Added Notifications Feature
  MovieVerse-Frontend/css/style.css
  index.html
  index.js
Labels: bug, documentation, enhancement, dependencies

#37 Enhanced notifications feature (#37)
  MovieVerse-Frontend/css/style.css
Labels: bug, documentation, enhancement, good first issue, dependencies

#42 Improved App SEO & Fixed Search Results Page
  404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/search.js
Labels: bug, documentation, enhancement, good first issue, dependencies

#43 Fix: Updated project documentation (#42)
  .github/README.md
  .github/SECURITY.md
  LICENSE
  index.html
  manifest.json
Labels: bug, documentation, enhancement, good first issue, dependencies

#44 Updated Project Documentation & Info
  LICENSE
Labels: bug, documentation, enhancement, good first issue, dependencies

#46 Updated Search Logic & Project Documentation
  MovieVerse-Frontend/js/search.js
  images/README.md
  utils/README.md
Labels: bug, documentation, enhancement, good first issue, dependencies

#47 Enhanced App's SEO
  .github/README.md
  404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  index.html
  microfrontend-layout.html
Labels: documentation, enhancement, dependencies

#48 Updated Responsive Design
  LICENSE
  MovieVerse-Frontend/404.html
  MovieVerse-Frontend/App.vue
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/index.html
  MovieVerse-Frontend/index.js
  MovieVerse-Frontend/microfrontend-layout.html
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies

#50 Enhanced mobile app & Updated project documentation
  MovieVerse-Frontend/README.md
  MovieVerse-Mobile/README.md
  MovieVerse-Mobile/www/MovieVerse-Frontend/README.md
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/index.html
  MovieVerse-Mobile/www/index.js
  MovieVerse-Mobile/www/launch-screen.html
Labels: bug, documentation, enhancement, good first issue, dependencies

#51 Fixed Watchlist Movement and Pinning Logic
  MovieVerse-Frontend/css/style.css
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Frontend/js/company-details.js
  MovieVerse-Frontend/js/director-details.js
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Frontend/js/search.js
  images/universe-1-low.png
  images/universe-1-medium.png
  images/universe-1-very-low.png
  index.html
  index.js
Labels: bug, documentation, enhancement, good first issue, dependencies
