Repository hoangsonww/The-MovieVerse-Database, pull requests merged in 2024-03, with the labels that each got.

#56 Added Dynamic Loading Logic
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/movie-timeline.js
Labels: bug, documentation, enhancement, good first issue, dependencies

#57 Enhanced SEO & Updated Favorites/Watchlists Logic
  MovieVerse-Frontend/css/trivia.css
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/analytics.js
  MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/user-profile.js
  MovieVerse-Mobile/www/.dockerignore
  MovieVerse-Mobile/www/.gitignore
  MovieVerse-Mobile/www/App.vue
  MovieVerse-Mobile/www/MovieVerse-Frontend/README.md
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/trivia.css
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/analytics.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/favorites.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/user-profile.js
  MovieVerse-Mobile/www/Pipfile
  MovieVerse-Mobile/www/Pipfile.lock
  MovieVerse-Mobile/www/index.html
  MovieVerse-Mobile/www/launch-screen.html
  MovieVerse-Mobile/www/manifest.json
  MovieVerse-Mobile/www/microfrontend-layout.html
  MovieVerse-Mobile/www/package-lock.json
  MovieVerse-Mobile/www/package.json
  MovieVerse-Mobile/www/robots.txt
  index.html
  manifest.json
  package-lock.json
  package.json
Labels: bug, documentation, enhancement, good first issue, dependencies

#59 Fixed Mobile App
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/company-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/create-account.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/director-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/favorites.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/inception.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/offline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/search.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/settings.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/trivia.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/favorites.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/service-worker.js
Labels: bug, documentation, enhancement, good first issue, dependencies

#61 Enhanced homepage notifications
  MovieVerse-Frontend/css/style.css
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies

#63 Homepage enhancements
  .github/README.md
  404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  index.html
Labels: bug, documentation, duplicate, enhancement, dependencies, feature

#64 Enhanced Search Feature for Homepage
  404.html
  MovieVerse-Frontend/css/style.css
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#65 Enhanced Search UI
  404.html
  MovieVerse-Frontend/404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/style.css
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/company-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/create-account.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/director-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/favorites.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/inception.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/offline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/search.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/settings.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/trivia.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/index.html
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#66 Enhanced search feature
  404.html
  index.html
Labels: documentation, enhancement, good first issue, dependencies, feature

#69 Enhanced App Functionalities
  404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/about.js
  MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Frontend/js/analytics.js
  MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Frontend/js/christopher-nolan.js
  MovieVerse-Frontend/js/company-details.js
  MovieVerse-Frontend/js/director-details.js
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/inception.js
  MovieVerse-Frontend/js/leonardo-dicarprio.js
  MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Frontend/js/movie-match.js
  MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Frontend/js/search.js
  MovieVerse-Frontend/js/tv-details.js
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/create-account.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/settings.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/about.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/analytics.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/christopher-nolan.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/company-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/director-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/favorites.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/inception.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/leonardo-dicarprio.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-match.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/search.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/tv-details.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#70 Enhanced Search Functionality
  MovieVerse-Frontend/html/search.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/search.html
  MovieVerse-Mobile/www/index.html
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#71 Updated Project Documentation
  .github/LICENSE
  .github/README.md
  MovieVerse-Databases/LICENSE
Labels: bug, documentation, enhancement, dependencies, feature

#73 Homepage Enhancements
  .github/README.md
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/package-lock.json
  MovieVerse-Frontend/package.json
  MovieVerse-Mobile/.idea/.gitignore
  MovieVerse-Mobile/.idea/workspace.xml
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/cordova.js
  MovieVerse-Mobile/platforms/android/app/src/main/assets/www/utils/README.md
  MovieVerse-Mobile/platforms/android/platform_www/cordova.js
  MovieVerse-Mobile/platforms/ios/platform_www/cordova.js
  MovieVerse-Mobile/platforms/ios/www/cordova.js
  MovieVerse-Mobile/platforms/ios/www/utils/README.md
  MovieVerse-Mobile/www/utils/README.md
  index.html
  utilities/LICENSE
  utilities/README.md
  utilities/applyFilterToVideo.c
  utilities/applyFilterToVideo.wasm
  utilities/colorInvertingVideo.c
  utilities/colorInvertingVideo.wasm
  utilities/countryCodeEnum.js
  utilities/countryCodeEnum.ts
  utilities/data.js
  utilities/data.ts
  utilities/errors.js
  utilities/errors.ts
  utilities/imageEnhancer.c
  utilities/imageEnhancer.wasm
  utilities/imageFilter.c
  utilities/imageFilter.wasm
  utilities/langCodeEnum.js
  utilities/langCodeEnum.ts
  utilities/redrawImage.c
  utilities/redrawImage.wasm
  utilities/twoLetterCountryCodes.js
  utilities/twoLetterLangCodes.js
  utilities/utilities.js
  utilities/utilities.ts
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#79 Enhanced Comments Logic
  MovieVerse-Frontend/js/comments.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#80 Enhanced chatbot logic
  .idea/.gitignore
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/js/chatbot.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#82 Enhanced SEO & Updated App Stylings
  .github/README.md
  1ee157648b374c35b55ea4685a90ecbe.txt
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/platforms/ios/MovieVerse.xcworkspace/xcuserdata/davidnguyen.xcuserdatad/UserInterfaceState.xcuserstate
  MovieVerse-Mobile/www/.dockerignore
  MovieVerse-Mobile/www/1ee157648b374c35b55ea4685a90ecbe.txt
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/config.yml
  MovieVerse-Mobile/www/sitemap.xml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#83 Updated documentation (#83)
  .github/README.md
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#85 Homepage Enhancements
  .idea/watcherTasks.xml
  1ee157648b374c35b55ea4685a90ecbe.txt
  MovieVerse-Frontend/css/index.scss
  MovieVerse-Frontend/css/navbar.scss
  MovieVerse-Frontend/css/profile.scss
  MovieVerse-Frontend/html/article.hbs
  MovieVerse-Frontend/html/movies-list.hbs
  MovieVerse-Frontend/html/profile.ejs
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#86 Homepage Enhancements
  404.html
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/index.scss
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/navbar.scss
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/profile.scss
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/article.hbs
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movies-list.hbs
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/profile.ejs
  MovieVerse-Mobile/www/index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#87 Enhanced UI Frontend
  MovieVerse-Frontend/App.vue
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#89 Enhanced Backend & Fixed Frontend
  MovieVerse-Databases/Data-Analysis/DataAnalysis.R
  MovieVerse-Databases/Data-Analysis/MovieDataVisualization.R
  MovieVerse-Databases/Data-Analysis/MovieSentimentAnalysis.R
  MovieVerse-Databases/Data-Analysis/README.md
  MovieVerse-Databases/README.md
  MovieVerse-Mobile/www/MovieVerse-Databases/Data-Analysis/DataAnalysis.R
  MovieVerse-Mobile/www/MovieVerse-Databases/Data-Analysis/MovieDataVisualization.R
  MovieVerse-Mobile/www/MovieVerse-Databases/Data-Analysis/MovieSentimentAnalysis.R
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#91 Added Netlify Config
  .gitignore
  Dockerfile
  project-config/.netlify/netlify.toml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#93 Enhanced Homepage & Updated Project Documentation
  .github/README.md
  404.html
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/index.html
  MovieVerse-Mobile/www/index.js
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#94 Minor Repo Enhancements
  .github/CODE_OF_CONDUCT.md
  .github/SECURITY.md
  .github/STYLEGUIDE.md
  images/README.md
  index.js
  microfrontend-layout.html
  sitemap.xml
Labels: bug, documentation, duplicate, enhancement, good first issue, dependencies, feature

#95 Enhanced Homepage UI
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#99 Homepage Enhancements & Layout Updates
  MovieVerse-Frontend/css/style.css
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Frontend/js/search.js
  MovieVerse-Frontend/js/tv-details.js
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#100 Fixed UI Layout
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/support.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#101 Homepage Enhancements & Updated Frontend
  MovieVerse-Frontend/css/trivia.css
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Frontend/js/quiz.js
  MovieVerse-Frontend/js/search.js
  index.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#104 Added AI-Powered Recommendations
  .github/README.md
  404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/about.js
  MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Frontend/js/add-to-favorites.js
  MovieVerse-Frontend/js/analytics.js
  MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Frontend/js/christopher-nolan.js
  MovieVerse-Frontend/js/company-details.js
  MovieVerse-Frontend/js/director-details.js
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/inception.js
  MovieVerse-Frontend/js/leonardo-dicarprio.js
  MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Frontend/js/movie-match.js
  MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Frontend/js/search.js
  MovieVerse-Frontend/js/tv-details.js
  index.html
  index.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#105 Homepage Enhancements
  404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Frontend/html/analytics.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Frontend/html/company-details.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/director-details.html
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/inception.html
  MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/offline.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/add-to-favorites.js
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#106 Homepage Enhancements & Personalized Recommendation Updates
  MovieVerse-Frontend/html/reset-password.html
  index.html
  index.js
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#107 Enhanced Movie Recommendation Service
  404.html
  MovieVerse-Frontend/html/404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Frontend/js/director-details.js
  MovieVerse-Frontend/js/favorites.js
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#108 Homepage Enhancements
  MovieVerse-Frontend/css/LICENSE
  MovieVerse-Frontend/html/LICENSE
  MovieVerse-Frontend/js/LICENSE
  MovieVerse-Frontend/react/LICENSE
  MovieVerse-Frontend/tests/LICENSE
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#110 Homepage Enhancements & Updated Project Documentation
  .github/README.md
  project-config/.netlify/LICENSE
  project-config/.netlify/README.md
  project-config/LICENSE
  project-config/README.md
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#111 Update: Updated app stylings (#110)
  MovieVerse-Frontend/css/style.css
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#124 Homepage Enhancements
  MovieVerse-Frontend/css/style.css
  MovieVerse-Frontend/html/favorites.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/search.html
  index.html
  package.json
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#125 Homepage Enhancements
  404.html
  App.vue
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Frontend/html/create-account.html
  MovieVerse-Frontend/html/feedback.html
  MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Frontend/html/settings.html
  MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Frontend/html/support.html
  MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Frontend/html/trivia.html
  MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Frontend/js/about.js
  MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Frontend/js/analytics.js
  MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Frontend/js/christopher-nolan.js
  MovieVerse-Frontend/js/company-details.js
  MovieVerse-Frontend/js/director-details.js
  MovieVerse-Frontend/js/favorites.js
  MovieVerse-Frontend/js/inception.js
  MovieVerse-Frontend/js/leonardo-dicarprio.js
  MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Frontend/js/movie-match.js
  MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Frontend/js/quiz.js
  MovieVerse-Frontend/js/search.js
  MovieVerse-Frontend/js/tv-details.js
  index.html
  index.js
  sitemap.xml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#126 Homepage Enhancements & Updated Project Documentation
  MovieVerse-APIs/README.md
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#128 Fix: Updated homepage (#125)
  .github/README.md
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#129 Homepage enhancements
  MovieVerse-APIs/config.yml
  MovieVerse-Backend/config.yml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#130 Homepage enhancements
  MovieVerse-APIs/config.yml
  MovieVerse-Backend/config.yml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#131 Homepage enhancements
  MovieVerse-Databases/config.yml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#132 Fix: Updated homepage (#125)
  MovieVerse-Design/config.yml
Labels: documentation, enhancement, dependencies

#133 Fix: Updated homepage (#125)
  MovieVerse-Frontend/config.yml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#134 Homepage enhancements
  MovieVerse-Middleware/config.yml
Labels: bug, documentation, dependencies

#136 Homepage enhancements
  MovieVerse-Scripts/config.yml
Labels: documentation, dependencies

#137 Fix: Updated mobile app (#125)
  project-config/config.yml
Labels: bug, documentation, dependencies

#138 Homepage enhancements
  utilities/config.yml
Labels: bug, documentation, dependencies

#139 Fix: Updated Databases (#138)
  MovieVerse-Databases/Data-Analysis/.flake8
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#140 Update: Updated Servers & Backend (#140)
  MovieVerse-Backend/README.md
Labels: documentation, enhancement, good first issue, dependencies, feature

#141 Update: Updated Images (#140)
  images/config.yml
Labels: bug, documentation, dependencies

#142 Update: Updated Backend & Servers (#142)
  MovieVerse-Backend/.dockerignore
Labels: bug, documentation, dependencies

#144 Update: Updated Frontend UI (#142)
  MovieVerse-Frontend/.dockerignore
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#145 Homepage enhancements
  MovieVerse-Mobile/.dockerignore
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#146 Fix: Updated project config (#145)
  project-config/.dockerignore
Labels: documentation, enhancement, good first issue, dependencies, feature

#147 Fix: Updated utilities (#145)
  utilities/.dockerignore
Labels: bug, documentation, dependencies

#148 Fix: Updated PWAs (#147)
  manifest.json
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#149 Homepage enhancements
  MovieVerse-Mobile/www/404.html
  MovieVerse-Mobile/www/App.vue
  MovieVerse-Mobile/www/MovieVerse-Frontend/.dockerignore
  MovieVerse-Mobile/www/MovieVerse-Frontend/Dockerfile
  MovieVerse-Mobile/www/MovieVerse-Frontend/README.md
  MovieVerse-Mobile/www/MovieVerse-Frontend/config.yml
  MovieVerse-Mobile/www/MovieVerse-Frontend/css/style.css
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/about.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/actor-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/analytics.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/api_fails.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/chatbot.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/christopher-nolan.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/company-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/create-account.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/director-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/favorites.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/feedback.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/inception.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/leonardo-dicaprio.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-match.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/offline.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/privacy-policy.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/reset-password.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/search.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/settings.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/sign-in.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/support.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/terms-of-service.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/trivia.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/tv-details.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/html/user-profile.html
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/about.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/actor-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/analytics.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/chatbot.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/christopher-nolan.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/company-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/director-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/favorites.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/inception.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/leonardo-dicarprio.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-details.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-match.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/movie-timeline.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/quiz.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/search.js
  MovieVerse-Mobile/www/MovieVerse-Frontend/js/tv-details.js
  MovieVerse-Mobile/www/index.html
  MovieVerse-Mobile/www/index.js
  MovieVerse-Mobile/www/manifest.json
  MovieVerse-Mobile/www/microfrontend-layout.html
  MovieVerse-Mobile/www/sitemap.xml
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#150 Updated mobile app & homepage (#150)
  MovieVerse-Mobile/www/index.html
  index.html
Labels: bug, documentation, enhancement, good first issue, dependencies, feature

#151 Homepage Enhancements
  MovieVerse-Databases/.gitignore
  MovieVerse-Mobile/.gitignore
  sitemap.xml
Labels: documentation, enhancement, good first issue, dependencies, feature

#153 Update: Updated Sitemap & Dependencies (#150)
  404.html
  MovieVerse-Frontend/html/about.html
  MovieVerse-Frontend/html/movie-timeline.html
  MovieVerse-Frontend/html/search.html
  MovieVerse-Frontend/html/settings.html
  index.html
  package-lock.json
  package.json
Labels: bug, documentation, enhancement, good first issue, dependencies, feature
